[build]
  publish = "sistemafinanceiro"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/pluggy/:splat"
  to = "/.netlify/functions/pluggy-token/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
